### ISSUE TITLE
Ordering Permissions & Menu Sync

### ISSUE THREAD

**Issue by kylephillips** [kylephillips/wp-nested-pages#102]
When an editor has been given permissions to reorder pages, the menu is not syncing.

**Comment by ClementRoy** [comment]
Same problem here

**Comment by Flipo** [comment]
I have the same problem. After giving an editor the permissions to reorder pages the menu syncing is totally broken now. The menu wont sync anymore. Even after removing the permissions and checking the checkbox to sync menu as an administrator the menu won't sync. Changing the pages order or hiding a page won't sync.

**Comment by nextbigleap** [comment]
I can also confirm this. Sync option isnt available or works when used as an editor.
