### ISSUE TITLE
Permissions error when deleting page

### ISSUE THREAD

**Issue by chadwick37** [kylephillips/wp-nested-pages#104]
I'm using nested pages on a custom post type only. I'm not using it on Pages. When a page is trashed or deleted I'm redirected to this page: `http://domain.com/wp-admin/edit.php?post_type=page&trashed=1&ids=844&page=nestedpages` given an error, `You do not have sufficient permissions to access this page.` The page is successfully trashed or deleted I'm just given this error.

**Comment by kylephillips** [comment]
It's been a while, but I've been unable to recreate this bug. If it continues to happen after the next release, any additional info you could provide would be helpful.
