### ISSUE TITLE
No modal if the last element is in the trash

### ISSUE THREAD

**Issue by ClementRoy** [kylephillips/wp-nested-pages#105]
If the very last element of the list (not a nested one) the quick edit modal doesn't show up because the DOM is not generated correclty.
The correct DOM (but you already know it) is:
![capture d ecran 2015-04-18 a 14 41 07](https://cloud.githubusercontent.com/assets/555607/7215457/441ab1f4-e5d9-11e4-9477-9443499be2e4.png)

But, if the last item is in the trash, here is the DOM
![capture d ecran 2015-04-18 a 14 41 39](https://cloud.githubusercontent.com/assets/555607/7215456/4418963a-e5d9-11e4-91be-a928bf8866e1.png)

This is because the < ol > element is not closed correctly. 

I found a quick bugfix, because in this case the function parentTrashed was returning true and should be returning false, I added a condition || $pages->query['post_parent'] == 0 :

	/**
	* Parent Trash Status
	* @param WP Query object
	* @return boolean
	*/
	private function parentTrashed($pages)
	{
		//if ( !isset($pages->query['post_parent']) ) return false;
		if ( !isset($pages->query['post_parent']) || $pages->query['post_parent'] == 0 ) return false; // Bugfix
		if ( get_post_status($pages->query['post_parent']) == 'trash' ) return true;
		return false;

	}

/app/Entities/Listing/Listing.php - l.336

**Comment by kylephillips** [comment]
Thanks for finding the bug (and the fix). It'll be included in the next release.
