### ISSUE TITLE
Feature Request: Ability to select a parent in "Add Multiple" modal

### ISSUE THREAD

**Issue by daltonrooney** [kylephillips/wp-nested-pages#108]
When editing a hierarchical post type, the default WP bulk editor has a select box for the post parent. I think it might be useful to be able to do the same when using the "Add Multiple" tool. Let's say I'm populating a "Services" section, with 10 sub-pages, adding all 10 sub-pages in a single modal would be extremely efficient.

**Comment by kylephillips** [comment]
If I understand your request correctly, this feature exists. By selecting the link icon on a specific row/page, that page will be set as the parent automatically. (as opposed to selecting "add multiple" at the top of the interface).
![addlinks](https://cloud.githubusercontent.com/assets/1779473/7997168/02e2e916-0af7-11e5-83a4-97b57b027345.jpg)

**Comment by daltonrooney** [comment]
You're absolutely right - clicking the "Add Child" button while hovering over the page does include this feature. I missed the plus sign in the modal window. Thanks!
