### ISSUE TITLE
Category Filtering

### ISSUE THREAD

**Issue by kylephillips** [kylephillips/wp-nested-pages#116]
Add category filtering capabilities to post types with categories enabled.

**Comment by nutyga** [comment]
Hi Kyle,

Thanks for a great plugin.  Does this capability allow ordering of posts within a category?

**Comment by kylephillips** [comment]
No, it doesn't. The comment above is for adding category "filtering" back into the admin view – just a way to filter the view.

The plugin doesn't really add any kind of custom ordering. It uses the "menu order" column in WP core and adds a UI to better manage it.
