### ISSUE TITLE
RedirectsFrontEnd in 1.5.3 breaks custom post types URLs

### ISSUE THREAD

**Issue by garrettjohnson** [kylephillips/wp-nested-pages#126]
Redirects front end breaks custom post types like The Events Calendar from Modern Tribe. It ends up appending a page_id to the query string.

**Comment by ianregister** [comment]
Also experiencing bugs in the front end using Tribe Events, CPTs, and Roots Bedrock, yet fine in backend. Issues replicable using 2015 theme and plugins disabled.
