### ISSUE TITLE
Add Child button does appear after page refresh

### ISSUE THREAD

**Issue by onetrev** [kylephillips/wp-nested-pages#133]
It looks like the "Add Child" option is only available after adding pages through the "Add Multiple" button and clicking the "Add" button so the modal closes and All Pages page stays open.

In other words, as soon as I refresh the "All Pages" page, the "Add Child" option is gone. Note: Chrome 45; WIndows 10

![snip_20150927110858](https://cloud.githubusercontent.com/assets/597601/10124404/43760776-6509-11e5-8b0b-b2608edf4d67.png)

Thank you!

**Comment by onetrev** [comment]
Any ideas on this one please? This is a pretty glaring bug. 

I need to create a ton of child pages but no Add Child page is present, as per screenshot above, as I've left the All Pages menu. It's frustrating because the button is there as mentioned, as soon as you create multiple pages, but then the button is gone when you refresh the "All Pages" page.

**Comment by daltonrooney** [comment]
+1

**Comment by onetrev** [comment]
Sorry to bump this, but it's a pretty key issue, but just wondering if this is a bug that is going to be fixed? Thank you very much!!

**Comment by onetrev** [comment]
Just wanted to add a video showing this issue. Very frustrating that "Add Child" is only available if you use "Add Multiple" and have not refreshed the page. Because once you refresh the page you are left with only the "Clone" option, can never Add Multiple child pages again. https://www.dropbox.com/s/skvvwhgy3paaowa/Recording%20%2341.mp4?dl=0

**Comment by nickfmc** [comment]
I can verify this issue appears when you select the Disable Menu Sync Completely option from the settings of nested pages.
