### ISSUE TITLE
Feature request: Generate new menu

### ISSUE THREAD

**Issue by ArchCarrier** [kylephillips/wp-nested-pages#138]
Sometimes the Nested Pages menu gets corrupted (maybe through plugin conflicts, it's very hard to reproduce), and when this happens it would be very helpful if there was a way to (re)generate the menu from the page hierarchy.

**Comment by kylephillips** [comment]
You can do this now.Visit Appearance > Menus and delete the menu.
Visiting the Pages listing with menu sync enabled will regenerate the menu.
There's a small bug that may crop up when doing this, where menu items are duplicated, but it will be fixed in the next release.

**Comment by ArchCarrier** [comment]
That's exactly what I did, and exactly what happened after I did it: duplicated menu items. I'm glad you're aware of this bug. Thanks, Kyle!

**Comment by ArchCarrier** [comment]
Kyle, would it be possible to release a new version? This bug that duplicates menu items is driving me nuts - every time after I change something on a page I have to delete the Nested Pages menu and generate a new one. Thanks!
