### ISSUE TITLE
Plugin not working well with very large sites.

### ISSUE THREAD

**Issue by sebastianthulin** [kylephillips/wp-nested-pages#144]
How about loading less pages in some way? Tested with very few top-level pages and loads of sub level pages. 

Etc. 
- Top
  - 700 sub pages  
- Top
  - 1200 sub pages 
- Top 
  - 1500 subpages  
- Top 
  - 50 subpages 

In this case, the "pages" admin menu will be very slow. Some ajax requests as sorting function will not work due to large $_POST[] object (APACHE limit)

**Comment by andri** [comment]
This still has not been fixed. Plugin is unusable for medium to large sites.

**Comment by kylephillips** [comment]
Duplicate of #127
