### ISSUE TITLE
Feature request: background syncing of nest moves

### ISSUE THREAD

**Issue by moofresh** [kylephillips/wp-nested-pages#155]
Currently if you drag a page to a different nested position, the 'rotating activity ball' spins away until it has saved the move, but you can't move other pages in the meantime.

On my site it takes about 20s to complete each move, and each new page has about 8 nested sub-pages which makes it take a bit of time to move stuff around.

It'd be really nice if it could 'stack up' requests (or save the position change faster), so we could rearrange a bunch of nested pages without waiting for the previous one to complete.

**Comment by kylephillips** [comment]
Closed with [6b5d9e5](https://github.com/kylephillips/wp-nested-pages/commit/6b5d9e585b2e3d8dd4f02011bfc3a8c4d4825a41). Not quite the same as a background queue, but should solve the problem.
