### ISSUE TITLE
Page Notes (only visible to backend/admin)

### ISSUE THREAD

**Issue by mehtuus** [kylephillips/wp-nested-pages#160]
On a site that I maintain, the client has a handful of pages where they do not want "titles" on the page. This of course leaves a blank line where the title should be. I use another plugin that allows me to add notes for individual pages. Under normal circumstances, the notes I use would have been the title of the page. These notes are visible from the admin's list of pages (not on the frontend), so it is simple to keep track of those pages and to know which page is which.

When viewing the list through Nested Pages, the notes are prevented from displaying (see image below). I can view the slug by clicking "quick edit" or I can go to "default pages" to bypass Nested Pages which will allow the other notes plugin to display properly.

Here is my question: _"Any chance for a simple page notes enhancement to Nested Pages that will only be visible from the admin area?"_

![ccf nested pages](https://cloud.githubusercontent.com/assets/1516885/19242126/d0f81d22-8edf-11e6-807a-9663e70b2e44.jpg)

**Comment by kylephillips** [comment]
Titles in the next version of the plugin will be filtered using the_title filter:
[see code](https://github.com/kylephillips/wp-nested-pages/blob/master/app/Views/partials/row.php#L29)

Hooking into that in your theme functions or custom plugin may be a more sustainable approach than creating something custom for this specific plugin.
