### ISSUE TITLE
Slow reordering

### ISSUE THREAD

**Issue by tillkruss** [kylephillips/wp-nested-pages#164]
Our sites is speedy, however when we drag and drop a page to change it's menu order, the request takes about 15 seconds. We have around 200 pages total.

**Comment by kylephillips** [comment]
If you're using the latest version, you can disable the auto menu sync.

Under settings > Nested Pages, enable both "Manually sync menu" and "Manually sync page order".

When you are finished reordering, click the "sync order", then the "sync menu" buttons, in that order. 

That way you won't have to wait for the saving process with each drag and drop.

**Comment by tillkruss** [comment]
Thanks!

In which file is the logic for this? Maybe I can speed up a little.

**Comment by kylephillips** [comment]
Unfortunately, the performance issue isn't limited to one file. I have started some performance enhancements on another branch… just haven't had a chance to merge in some of those to master.
