### ISSUE TITLE
Clone: child pages too

### ISSUE THREAD

**Issue by lkraav** [kylephillips/wp-nested-pages#165]
While https://wordpress.org/plugins/duplicate-post/ is nice, Nested Pages is better. Would be nice if Clone button had the ability clone a full tree of pages.

**Comment by lkraav** [comment]
@kylephillips are recent versions doing this now? We are noticing Clone button copying the full tree now, and aren't entirely sure whether it's WP-NP, or some other plugin providing integration.

**Comment by DaveWoody** [comment]
> @kylephillips are recent versions doing this now? We are noticing Clone button copying the full tree now, and aren't entirely sure whether it's WP-NP, or some other plugin providing integration.

Any new insights on this topic? Trying to clone a nested parent page gives me only the parent. Can you remember if a plugin helped u with this?

**Comment by tkyser-rodeo** [comment]
Following up on this too @kylephillips
