### ISSUE TITLE
Only Admin can Sort Entrys

### ISSUE THREAD

**Issue by Borsti26** [kylephillips/wp-nested-pages#167]
Hello,

since the new Update only Adminsitrator have the possiblity to sort the entrys via Drag & Drop.

Because you delete the following line in UserRepository.php
`if ( current_user_can('edit_theme_options') ) return true;`

Hopefully you can fix this in next release.

BR

**Comment by kylephillips** [comment]
User groups can be granted sort/order privileges by visiting settings > Nested Pages.
