### ISSUE TITLE
Recursive function on existing installs when updating from version 1.5 to 1.6

### ISSUE THREAD

**Issue by Blake-C** [kylephillips/wp-nested-pages#168]
I recently had a site go down a few days after updating WordPress and some plugins. I tracked the issue down to my findings in the following document. 

We had the nested pages plugin already installed and I believe the plugin tried to recreate a menu with the same name of an existing menu. This caused a function to loop on itself since there was no menu ID in the database, instead there was an error message. I turned on debugging while tracking the issue down locally and the following message displayed: 

Xdebug: Fatal error: Maximum function nesting level of '100' reached, aborting! 

I did not track the issue beyond what is in the following document:

[NestedPagesPluginIssue.pdf](https://github.com/kylephillips/wp-nested-pages/files/586315/NestedPagesPluginIssue.pdf)

**Comment by Blake-C** [comment]
Here are the detail on my setup as well.

![setup](https://cloud.githubusercontent.com/assets/5287911/20224931/7bdc49ea-a806-11e6-82a5-8a74d100ccab.jpg)

**Comment by kylephillips** [comment]
Thanks for the detailed write-up. I'll take a look at what might be going on, but I'm not sure why the code outlined would produce the error. The plugin update itself does not trigger a regeneration of the menu.

**Comment by wgroenewold** [comment]
When I upgraded from 1.6.5.2 to 1.7.1 the same happened to me. Luckily I found this thread since I was pulling hairs out already. The weird thing is that I have the "Sync Nested Pages" completely disabled and it still breaks. I think it shouldn't even load this value then, but somehow it does and breaks.

**Comment by wgroenewold** [comment]
Also: if you change the value in the DB but somebody loads the page it writes back the error. 

I think fixing it would be something like this:

```
private function createNewMenu()
	{
		$check_option = get_option('nestedpages_menu');
		if(!is_numeric){
			$menu = wp_get_nav_menu_object('Nested Pages');
			update_option('nestedpages_menu', $menu->term_id);
		}

		$is_menu = wp_get_nav_menu_object('Nested Pages');
		if($is_menu === false){
			$menu = wp_create_nav_menu('Nested Pages');	
			update_option('nestedpages_menu', $menu->term_id);
		}
	}
```
