### ISSUE TITLE
When using the same slug for nested pages, the wrong content is being displayed

### ISSUE THREAD

**Issue by loekwetzels** [kylephillips/wp-nested-pages#171]
When using the same slug for nested pages, the wrong content is being displayed. Example:

http://example.com/mainpage1/sub
http://example.com/mainpage2/sub > content of mainpage1/sub is being displayed
http://example.com/mainpage2/sub2 > correct content is being displayed

**Comment by kylephillips** [comment]
Closing this issue, as it was addressed a few versions back
