### ISSUE TITLE
First row is blank

### ISSUE THREAD

**Issue by tomlongo** [kylephillips/wp-nested-pages#175]
Since version 1.5.4 I'm having some odd display issues on the post listing page. I thought maybe one of my CSS files were conflicting with the nested pages plugin, but even on a fresh WP install I'm getting a blank row as the first post, as demonstrated in the attached screenshot:

<img width="1284" alt="screen shot 2017-01-30 at 12 40 46 pm" src="https://cloud.githubusercontent.com/assets/1435382/22410554/af41ee08-e6e9-11e6-9e3f-ccfcb8b587bc.png">

The above screenshot was on a fresh WP 4.7.2 in Chrome  55.0.2883.95 with no other plugins activated, and the Twenty Seventeen theme. 

Not sure if this is something unique to me or others are experiencing this issue?

**Comment by kylephillips** [comment]
The row isn't actually a page/post row. It is for bulk actions.
