### ISSUE TITLE
WordPress black side and top nav not visible when Nested Pages is activated

### ISSUE THREAD

**Issue by noahkuhn** [kylephillips/wp-nested-pages#178]
WordPress black side and top nav not visible when Nested Pages is activated. It pops in if you click on the page somewhere or hover over a menu item (when it's invisible). It doesn't happen in every section. Noticed on these at least: 

- Dashboard
- Appearance
- Appearance > Widgets
- Tools

Please see screen shot. This started in a recent version. If I deactivate Nested Pages it goes away. Is this plugin still in active development?

![screen shot 2017-02-28 at 9 18 57 am](https://cloud.githubusercontent.com/assets/1133909/23408832/797d44b0-fd97-11e6-9ab2-1dc6018a7808.png)

**Comment by kylephillips** [comment]
I haven't seen this on any of the sites I'm running, all up to date.

Yes, the plugin is under active development.

**Comment by noahkuhn** [comment]
Thanks Kyle. I'm seeing it on nearly every site I've tested, but to be fair it does not happen on a few too. I supposed I could cross reference what other plugins are installed to see if there is some other problem, but considering the error goes away when this is turned off, I figured I'd start here. I have a screen video recording of the issue. Can I email it somewhere (rather than post publicly?).

**Comment by noahkuhn** [comment]
I just ran a test on a basic site. WP 4.7.2, Nested Pages 1.6.5.2. I deactivated all other plugins and loaded up the Dashboard page. The navigation bars did not show until I moved my mouse over them. I am on Sierra 10.12.2, and it does seem to only be an issue on Safari, 10.0.2 (12602.3.12.0.1). I tried Chrome and Firefox and could not reproduce

**Comment by noahkuhn** [comment]
Any thoughts on this? Have you been able to reproduce on Safari?  Not a show-stopper, but it's pretty annoying...
