### ISSUE TITLE
Pages that are in draft still showing up.

### ISSUE THREAD

**Issue by leviatorkilsheyggi** [kylephillips/wp-nested-pages#182]
Hi

We love and use Nested pages on multiple sites. We recently discovered that pages that our clients mark as draft(not published), are still showing up in the frontend navigation. Our permalink settings are postname `example.com/sample-post/`, but unpublished pages in draft are still showing up with plain permalink `example.com/?p=123`. What simple thing are we missing here?

Thanks in advance
Levi

**Comment by kylephillips** [comment]
I've been unable to reproduce this issue. If you're still having problems, I would recommend regenerating the nav menu
* Uncheck "Sync Menu" in the NP interface
* Delete the "Nested Pages" menu under Appearance > Menus
* Recheck "Sync Menu" in the NP interface. This will regenerate the menu
