### ISSUE TITLE
Plugin notification causes UI glitch

### ISSUE THREAD

**Issue by onetrev** [kylephillips/wp-nested-pages#193]
Attached screenshot details it well, but the Woocommerce -> Stripe notification causes the Nested Pages "Add New" and "Add Multiple" buttons to not appear in the correct place. Not sure if this happens with other plugin notices. And if I clear the notice, everything returns to normal. Not a biggie, but definitely a minor bug. Thanks!!

![capture](https://cloud.githubusercontent.com/assets/597601/26432831/e2d123bc-4141-11e7-830d-52bd9c22fa63.PNG)

**Comment by kylephillips** [comment]
Noted
