### ISSUE TITLE
esc_url adds http: to search bar

### ISSUE THREAD

**Issue by joetek** [kylephillips/wp-nested-pages#198]
When you search in the Nested Tables admin page, the search page loads, and pre-populates the search field with "http://".

For example, when searching for "sample", it displays "http://sample - 

![nestedtables-search](https://cloud.githubusercontent.com/assets/1659626/26736317/8b2adcd6-4793-11e7-90ec-c1a5a7e8f691.png)

In /app/Views/partials/tool-list.php, line 139, the display value is filtered using esc_url() which adds a protocol to the search value.

**Comment by kylephillips** [comment]
Fixed in ddcea9d
