### ISSUE TITLE
Custom column support

### ISSUE THREAD

**Issue by hatsumatsu** [kylephillips/wp-nested-pages#203]
The changelog states that custom admin columns are available since v 1.6.4:

`````
Custom columns are now supported. Visit Settings > Nested Pages > Post Types 
to enable and order custom columns for each post type. Columns made available 
through the appropriate WordPress filters are available for selection, along with 
any taxonomies enabled for the post type.
`````
Somehow I can't find the setting, is this featured included in v 1.7.1 ?

**Comment by kylephillips** [comment]
Error reports were pouring in that I couldn't replicate, so I had to remove that feature. It will eventually make it back in
