### ISSUE TITLE
Gutenberg integration

### ISSUE THREAD

**Issue by lkraav** [kylephillips/wp-nested-pages#204]
Hey Kyle. You think we could add a button in the list row that opens the post editor in Gutenberg mode (if it's installed)? It's a bit of a hassle to switch out of Nested mode.

**Comment by kylephillips** [comment]
I would suggest using the `nestedpages_edit_link` filter for this.

[Here is an example](https://gist.github.com/kylephillips/cab2dae551fb091ae0c4c2d176c00cab)

**Comment by lkraav** [comment]
Well, this would lose the ability to pick the editor on the go. Here's a super crude hack for `app/Views/partials/row.php`:

```
<a href="<?php echo str_replace( [ 'post=', 'action=edit' ], [ 'post_id=', 'page=gutenberg' ], apply_filters('nestedpages_edit_link', get_edit_post_link(), $this->post) ); ?>" class="page-link page-title">
            <span class="title"><em>Gutenberg</em></span>
        </a>
```

Based on the learnings here, it'd really be useful if `Edit` span would be its own separate link, perhaps controlled by a filterable `$actions` variable, so people could add their own (although not sure at all how widely used this feature would be). Still, LOC difference would be negligible and nothing would really regress.

I could look to whip something up at a PR level.

**Comment by kylephillips** [comment]
I may look into adding a separate filter for the edit link, but since Gutenberg is still in dev/testing mode, and slated for core eventually, I'd rather not hard-code a link/button in the NP interface.

**Comment by lkraav** [comment]
PS Gutenberg 0.5.0 is soon going to take yet another step towards becoming the main editor https://github.com/WordPress/gutenberg/pull/1797
