### ISSUE TITLE
Page ordering not alphabetical even with order set to 0

### ISSUE THREAD

**Issue by joelyoder** [kylephillips/wp-nested-pages#206]
We are using Nested Pages on a large site to help navigate the 400+ pages we have. We are using our own navigation menu configuration and we have "Manually sync page order" and "Disable menu sync completely" checked.

Since we do not use the menu feature, we want all pages to be sorted alphabetically. Even on sections where the page order is set to 0 on every page, they still appear in the the order of creation. Toggling the "Manually sync page order" setting off does not change anything either.

**Comment by s28491** [comment]
I have similar issue, please see my workaround on link: [https://wordpress.org/support/topic/sort-pages-in-category-archive-exactly-as-in-admin/#post-9758988](https://wordpress.org/support/topic/sort-pages-in-category-archive-exactly-as-in-admin/#post-9758988). 

In short, a hook code needs to be added to functions.php, plus you need to manually save the Menu in Appearance > Menus. Hope it helps.

**Comment by kylephillips** [comment]
Once version 3 is released, you will have the option to set a default "Order by" and "Order" parameter for all post types, including pages. 

Nested Pages uses the standard "menu_order" post field for ordering, just like core. 

For this reason, drag and drop reordering will not be available if anything other than "Menu Order" in ascending order is selected. 

In your case, you will have the option of setting the default "order by" to title, with ascending or descending order.
