### ISSUE TITLE
No post list displayed for some post types

### ISSUE THREAD

**Issue by daltonrooney** [kylephillips/wp-nested-pages#209]
I have Nested Pages installed on a site with about 10 different content types. The post listing is not working for two CPTs, and the nested view is empty. The default view looks fine.

![screen shot 2017-09-13 at 11 20 31 am](https://user-images.githubusercontent.com/742045/30393631-a36b56f8-9875-11e7-9e62-8e1b5294da55.jpg)

WordPress 4.8.1, Nested Pages 2.0.1. PHP 7.0.3.

Apparently [others are experiencing this as well](https://wordpress.org/support/topic/plugin-not-working-after-wordpress-4-8-1-update/)? Happy to provide additional info for troubleshooting.

**Comment by kylephillips** [comment]
Would you mind trying a patched version, found here:
https://github.com/kylephillips/wp-nested-pages/issues/208

I've had many reports, but I've yet to be able to reproduce.

**Comment by daltonrooney** [comment]
Sorry I should have mentioned, I did try that patch with no luck. I don't see any PHP or SQL errors, either.

**Comment by kylephillips** [comment]
A couple of questions that may help…

- How is your Events post type above being registered? 
- Do you know what version of MySQL you are running?
- What taxonomies are registered for the event post type, and how are they being registered? What type are they (flat vs hierarchical)?

**Comment by kylephillips** [comment]
If your Events post type is registered with the Tribe plugin (Events Calendar), adding a suppress_filters argument from [this](https://github.com/kylephillips/wp-nested-pages/commit/aa8c3fe7717f5c41e151adc4d54c230904c9b5a3) patch may clear things up.

They apply filters to the WP_Query that limits the results based on some meta data (event dates), so that may prevent events from displaying. The suppress_filters argument removes those filters from that instance.

I'm still attempting to recreate the general issue of some CPTs not displaying.

**Comment by kylephillips** [comment]
Updated possible fix to try:
https://github.com/kylephillips/wp-nested-pages/releases/tag/2.0.1.1

Note, the events filter above will not work on this release. If this resolves the primary issue, I'll post a gist for removing the events filter specifically.

**Comment by daltonrooney** [comment]
We're not using Events Calendar, it's a standard CPT registered with `register_post_type()`.

I think I may have found the culprit, we also have a custom taxonomy. Here's the code we use for that:

`$args = array(
        'hierarchical'      => true,
        'labels'            => $labels,
        'show_ui'           => true,
        'show_admin_column' => true,
        'query_var'         => true,
        'rewrite'            => array( 'slug' => 'get-involved/events/category', 'with_front' => false )
    );

    register_taxonomy( 'event-cat', array( 'event' ), $args );`

When I deactivate that taxonomy, the post list for the events CPT is visible again.

**Comment by kylephillips** [comment]
This should be resolved in v2.0.2

**Comment by daltonrooney** [comment]
Confirmed, thanks! 👍
