### ISSUE TITLE
Published pages showing up in Trash

### ISSUE THREAD

**Issue by louiswalch** [kylephillips/wp-nested-pages#217]
I just set up a new Wordpress install, with Nested Pages installed of course. After adding a number of pages I noticed that the Published and Trash counts were incorrect. What's even worse, when I clicked to empty the Trash to remove the items I had actually trashed - it deleted all my Published pages as well. I had done a backup prior, not a huge deal.

I'm running version 2.0.4. All the pages were created via the Add New or Add Child buttons on the Page listing page. The items showing up as Trash are publicly viewable (actually published).

As a test, I upgraded a different Wordpress site which was already running Nested Pages to 2.0.4 and the count was correct, event after creating a new Page.

![pages_ __ _wordpress_and_pages_ _the_future_perfect_ _wordpress](https://user-images.githubusercontent.com/286013/33216113-858f55c6-d100-11e7-9eef-9e5b4f370b8a.png)

**Comment by kylephillips** [comment]
I've been unsuccessful at replicating this bug on both current and fresh installs with core v4.9.6 and NP v3.0.2.

If this pops up again, please reopen with any additional info you may have.
