### ISSUE TITLE
Infinite loop (?) error after upgrading to WP 4.9.5

### ISSUE THREAD

**Issue by trollsyn** [kylephillips/wp-nested-pages#227]
Hi,

After running the latest updates on all plugins and WP core, the browser throws an `ERR_EMPTY_RESPONSE` on all pages I try to access (wp-admin still works fine).

When I enable `WP_DEBUG` and try to access any page, I see an endless list of the following error:

```
Notice: Object of class WP_Error could not be converted to int in /var/www/html/wp-includes/taxonomy.php on line 869
```

I tried disabling all other plugins on the site, but the problem still occurs.

**Environment:**
Wordpress 4.9.5
Nested Pages 2.0.4
PHP 5.6.17
MySQL 5.5.46

Regards,
Ørjan

**Comment by lkraav** [comment]
Yes, I've run into this bug several times. There's something that can go wrong with the taxonomy query and NP is failing to account for it. I haven't had the time to debug it in detail unfortunately and just turned NP for time being.

**Comment by lkraav** [comment]
Thanks @kylephillips
