### ISSUE TITLE
Actions / Filters / Hooks

### ISSUE THREAD

**Issue by hatsumatsu** [kylephillips/wp-nested-pages#233]
Does the plugin offer a hook or filter for when posts are re-ordered aka. the `menu_order` is saved?

**Comment by kylephillips** [comment]
Not currently, but an action should be doable in a future version.

A filter would be tricky because the synced menu depends on the menu_order. If menu_orders were hooked without taking that into account, things could get wonky.

**Comment by hatsumatsu** [comment]
Cool, an action is perfectly fine. (I'm syncing post data between sites in a WP network (multilingual setup...)
