### ISSUE TITLE
Default ordering of non-sortable post lists  

### ISSUE THREAD

**Issue by hatsumatsu** [kylephillips/wp-nested-pages#237]
I'm using Nested Pages for all my post_types including the non-sortable ones to unify the UI across post types (great feature!). Is there any way to modify the default order of these post lists? Usually I do this via the `pre_get_posts` hook and `is_admin()` but in the Nested Pages UI it doesn't have any effect.

**Comment by kylephillips** [comment]
Under the post type settings where you've enabled the post type, look for the row "Sort Options." Check the "Order By" option and you'll have the option of setting the initial ordering of the posts (used in conjunction with the "Order" option).

Note: drag and drop ordering will be disabled when the list is not ordered by "menu order".

**Comment by hatsumatsu** [comment]
Thanks for the info! So there is no way to hook into the query programmatically like with `pre_get_posts`? My use case is ordering a non-sortable post type by meta key / value ...
