### ISSUE TITLE
Feature Request: Ability to reorder posts in multiple post_types together

### ISSUE THREAD

**Issue by twaiiiin** [kylephillips/wp-nested-pages#239]
Hello there,

Here's a feature request : The ability to reorder the posts of multiple post_type alltogether would be great in **WP-Nested-Pages**. I'm looking for an admin page in the WP Dashboard to reorder all the posts from a set of post_types combined.

Would you consider adding a hook or a filter to allow other developer to properly modify the `$query_args` in `ListingQuery.php` ?

Thank you ! Have a nice day.

**Comment by kylephillips** [comment]
There is a filter on line 106 of `ListingQuery` where the query args are passed.

The filter name is `nestedpages_page_listing` and passes the query_args as the single parameter.

I would imagine ordering multiple post types at the same time may get squirrely. I'd disable the menu synchronization at the least before proceeding.

**Comment by twaiiiin** [comment]
I did not see it in the plugin documentation. I looked at the examples you posted on gist and I could do what I wanted. Thank you so much!
