### ISSUE TITLE
Redirects get_current_screen non-existent

### ISSUE THREAD

**Issue by cwuensche** [kylephillips/wp-nested-pages#244]
Hey,
For some reason, with some plugins, I run into an error "function get_current_screen() doesn't exist". So to fix this, I have wrapped this code around it

        if ( function_exists( 'get_current_screen' ) )
        {
    		$screen = get_current_screen();
    		if ( !$screen ) return;
        }

and that is in the file wp-nested-pages/app/Redirects.php. Maybe you could add that code in the functions like pageRestored(), linkDeleted($post_id) etc. etc.?

**Comment by lkraav** [comment]
That's probably not going to happen. Need a traceback copy-paste from your fatal error so it hopefully becomes clearer which plugin or theme conflict is responsible for causing it.

**Comment by kylephillips** [comment]
Agreed with @Ikraav, due to the function being called in hooks where it is available. I'm going to close this issue for now. If the error resurfaces and is related to the plugin, details to replicate would be great.
