### ISSUE TITLE
Buttons based on permissions

### ISSUE THREAD

**Issue by heydey** [kylephillips/wp-nested-pages#245]
Hello, 
Fantastic plugin! Only issue is, the "Add New" button gets printed for all roles - this should be conditional if the user has access to create a page. For example, A contributor shouldn't see the 'add new' button on pages.

Thanks,
Harv

**Comment by heydey** [comment]
Situation may be particular to our configuration.

**Comment by heydey** [comment]
Kyle, thank you for the update. 
In our workflow, the author doesn't have publishing privileges. Is there a way to override your canPublish() function with our own logic? 
Thanks,
Harv

**Comment by walle89** [comment]
I agree with @heydey, the downside with this solution is that it doesn't really work with custom post type if the goal is not allow users to publish posts and/or pages, but allow to do that for a cetacean post type.

Maybe it's possible to do something like this instead:
```php
/**
	* Can the user publish to post type
	*/
	public function canPublish($post_type = 'post')
	{
		return (bool)current_user_can("publish_{post_type}s");
	}
```
Or maybe add as a setting like you have done for storing?
