### ISSUE TITLE
Pages with custom status not listed

### ISSUE THREAD

**Issue by heydey** [kylephillips/wp-nested-pages#246]
Hello,
Pages that have custom post statuses are not listed. It looks like statuses are currently limited:
'post_status' => ['publish', 'pending', 'draft', 'private', 'future', 'trash'],

Can this be updated to allow for statuses created by other plugins ie "Approved", "Rejected"?

Thanks,
Harv

**Comment by kylephillips** [comment]
There is a filter available a few lines below that. You should be able to hook into that and alter the statuses.

The filter name is `nestedpages_page_listing` and accepts one argument, the query_args.
