### ISSUE TITLE
User Role Editor Pro Restrictions

### ISSUE THREAD

**Issue by brrn** [kylephillips/wp-nested-pages#247]
I'm using a plugin called User Role Editor Pro to restrict access to certain pages for certain users.

For example, user A only has access to page 1. When logged in as user A, I see only page 1 listed in "Default Pages", but the NP listing shows me all pages. Is there a work-around for this?

Maybe an option to disable the NP listing altogether for users other than Administrators?

Thanks!

**Comment by kylephillips** [comment]
There will be a couple of options in the next release. A new capability of `nestedpages_sort_$type` will be added, where $type is the post type name. This will allow you to control which users/roles have access to sorting through a plugin like user role editor (Don't have the pro version, so I haven't tested individual user access).

There will also be a new plugin setting for limiting access to the sort view by user role. For more options, a filter has been added `nestedpages_sort_view_$type`. This filter passes 2 arguments: `$grant_access` (bool) and `$roles` (array of roles assigned to the current user).
