### ISSUE TITLE
Error cloning serialised meta data

### ISSUE THREAD

**Issue by f4w-pwharton** [kylephillips/wp-nested-pages#249]
https://github.com/kylephillips/wp-nested-pages/blob/4084f5b957fa601044d2161f0407fc8749111c68/app/Entities/Post/PostCloner.php#L113

If the data is stored serialised, then the clone function seems to add it as a serialised string.

I think that is because get_post_meta / get_metadata doesn't call maybe_unserialize when you don't provide a $meta_key (i.e. ask for all the metadata).

Then when you call add_post_meta / add_metadata which calls maybe_serialize, it gets serialised again because of some WP back-compat stuff -
https://developer.wordpress.org/reference/functions/maybe_serialize/#source

**Comment by jaredhill4** [comment]
I was having the same issue.

This is especially important to be able to support repeater and flexible content fields in Advanced Custom Fields.

I have created a pull request with a fix for this.

@kylephillips, can you take a look when you get a chance and see about merging this in?

Here is the PR: #256
