### ISSUE TITLE
when using the "Replace Default Pages Menu" option & editing a page, the sidebar menu is not expanded (BUG)

### ISSUE THREAD

**Issue by mariodabek** [kylephillips/wp-nested-pages#250]
Traced this down to EnabledMenus.php line 66

`	private function loopEnabledTypes()
	{
		$c = 1; // Counter for position
		global $np_page_params;
		foreach($this->enabled_types as $key => $type){
			if ( $type->np_enabled !== true ) continue;
			if ( $type->replace_menu ) {
				$this->post_type = get_post_type_object($key);
				if ( (current_user_can($this->post_type->cap->edit_posts)) || ($this->user->canSortPages()) ){
					$this->addMenu($c);
					$this->addSubmenu();
					**$this->removeExistingMenu();**
				}
			} else {
				$default = new AdminSubmenuDefault($type);
				$np_page_params[$default->getHook()] = ['post_type' => $type->name];
			}
			$c++;
		}
	}`

**Comment by mariodabek** [comment]
I should be able to set it to have a nested view by default and not hide the side menu on single edit view

**Comment by raptor235** [comment]
👍
