### ISSUE TITLE
7.2 Fatal Error

### ISSUE THREAD

**Issue by raptor235** [kylephillips/wp-nested-pages#251]
Hey guys latest build caused a fatal error on WP Engine 7.2 install

PHP Fatal error: require_once(): Failed opening required '/nas/content/live/xxxx/wp-content/plugins/wp-nested-pages/vendor/composer/autoload_static.php' (include_path='.:/usr/share/php') in /nas/content/live/xxxx/wp-content/plugins/wp-nested-pages/vendor/composer/autoload_real.php on line 28,

**Comment by kylephillips** [comment]
How was the plugin installed? I'm running several sites on WP Engine and 7.2 without issue…

**Comment by raptor235** [comment]
I did a clone from here, ran composer on local version of php 7.2 pushed up via git to WPE and got a fatal error.

**Comment by kylephillips** [comment]
I would try downloading from the [WP repo](https://wordpress.org/plugins/wp-nested-pages/) and pushing that up. There are some manual changes in the composer-generated files to prevent namespace issues with other plugins. I know it's not optimal, but worth a try.

**Comment by raptor235** [comment]
Last I checked the version in the repo wasn't as up to date as this Git branch
