### ISSUE TITLE
Filter to customize submenu texts

### ISSUE THREAD

**Issue by twaiiiin** [kylephillips/wp-nested-pages#254]
Hello there,

Is there a filter to customize the "Nested View" and "Sort View" submenu texts by any chance?

Thank you ! Have a nice day.

**Comment by kylephillips** [comment]
This will be available in the next release.

The filter name is `nestedpages_sortview_text` and passes two args: the text/label and the post type (post type object). The label is returned.

Another filter will also be available for the "Default" link.
That filter name is `nestedpages_default_submenu_text ` and passes the same args (label and post type object(

**Comment by twaiiiin** [comment]
Thank you!

**Comment by twaiiiin** [comment]
Hello,

Do you have an example of using this filter? I can not make it work properly with Nested Pages v.3.0.10.

Thank you.
