### ISSUE TITLE
Gutenberg block attributes with HTML being removed

### ISSUE THREAD

**Issue by GLAJL** [kylephillips/wp-nested-pages#259]
Hello,
We have created a dynamic block where some html is added via an attribute. All has been working fine until we came to clone a page where on the cloned page we discoved that the backslashes have been removed.

This is how the original stored block looks:
`<!-- wp:gl-blocks/cta {"mainText":"\u003cp\u003eaaa\u003c/p\u003e"} /-->`

After the clone the block looks like this:
`<!-- wp:gl-blocks/cta {"mainText":"u003cpu003eaaau003c/pu003e"} /-->`

Wordpress version - 5.2.1
Nested Pages version - 3.0.11

**Comment by kylephillips** [comment]
Closed with e5d6132269e57369a2edc055e98e434d4cbd7acd

**Comment by kylephillips** [comment]
Closed with e5d6132269e57369a2edc055e98e434d4cbd7acd
