### ISSUE TITLE
"Disable menu sync completely" leaves some menu functions

### ISSUE THREAD

**Issue by dhuyck** [kylephillips/wp-nested-pages#272]
When "Disable menu sync completely" is checked, some menu-related functions are still visible, which confuses our users. Specifically:

- "Menu Options" tab in the quick-edit screen is still there
- "Display in Nested View" checkbox available in the quick-edit screen
- "Display in Nested View" toggles available in the bulk-edit screen

There may be others, but these are the ones we've had to squash with some jQuery.

**Comment by black-eye** [comment]
+1

**Comment by kylephillips** [comment]
This last commit addresses the issue of nav menu options. The "Display in Nested View" is independent from the nav menu. This option enables the ability to hide a post/page from the listing view while maintaining it's position/hierarchy.

The "Display in Nested View" option can be removed using the plugin settings:

1. Go to Settings > Nested Pages and select the "Post Types" tab.
2. Toggle the appropriate post type(s) settings
3. Find the line "Configure Standard Fields" and select the checkbox
4. Click the checkbox next to the "Hide in Nested Pages" option to remove the field
5. Save Changes and repeat for any applicable post type

This isn't currently applying to bulk edit, but that will be fixed.
