### ISSUE TITLE
Incomplete German translation (complete Mo/Po attached)

### ISSUE THREAD

**Issue by liveweltDigital** [kylephillips/wp-nested-pages#276]
The German translation of the Plug-In was not complete.
Many elements in the backend were only available in English. The language mix of German and English was confusing for our customers, so we translated the plugin.

The Mo/Po files are attached here ;-)
[wp-nested-pages-de_DE_MO.zip](https://github.com/kylephillips/wp-nested-pages/files/4193335/wp-nested-pages-de_DE_MO.zip)
[wp-nested-pages-de_DE_PO.zip](https://github.com/kylephillips/wp-nested-pages/files/4193336/wp-nested-pages-de_DE_PO.zip)

Best regards
Chris

**Comment by kylephillips** [comment]
Thank you Chris. The plugin has been expanded greatly since it first launched, when the original translations were provided. Do you have a wp.org handle or full name so that I can give you credit?

**Comment by liveweltDigital** [comment]
Hello Kyle,

thanks for your reply.
Our WordPress account is "liveweltdigital".

Regards
Chris

Von: Kyle Phillips <notifications@github.com>
Gesendet: Mittwoch, 8. April 2020 22:13
An: kylephillips/wp-nested-pages <wp-nested-pages@noreply.github.com>
Cc: livewelt digital <digital@livewelt.de>; Author <author@noreply.github.com>
Betreff: Re: [kylephillips/wp-nested-pages] Incomplete German translation (complete Mo/Po attached) (#276)


Thank you Chris. The plugin has been expanded greatly since it first launched, when the original translations were provided. Do you have a wp.org handle or full name so that I can give you credit?
