### ISSUE TITLE
Hide from Nested Pages in admin should also apply to synced menu

### ISSUE THREAD

**Issue by bkeplinger** [kylephillips/wp-nested-pages#294]
I have more pages on my site than I want in my navigation, so I checked Hide in Nested Pages in admin. To my surprise these pages were still on the auto-synced menu. To get around this I set all of the pages I didn’t want to see in the navigation to Draft, a less-than-satisfactory solution.

Except for this one quirk I love the plugin.

**Comment by teomalchio** [comment]
Hi, I had the same issue, then I saw the Menu Options tab (into quick edit) and voila! "hide in navigation menu"! It works!

**Comment by teomalchio** [comment]
I see now your question was 4 september 😅

**Comment by kylephillips** [comment]
Closing this, as it's addressed above (separate options available)
