### ISSUE TITLE
"Posts" menu do not work.

### ISSUE THREAD

**Issue by timotheemoulin** [kylephillips/wp-nested-pages#295]
When using NestePages on the basic "post" type, the menu doesn't keep the original submenus.

Instead, the menu link is changed and no more submenus are available.

This is due to a wrong check here https://github.com/kylephillips/wp-nested-pages/blob/2d980b627b98f9bf1f025ca03acf9abd062f791b/app/Entities/AdminMenu/AdminSubmenu.php#L74

Instead, the line should be 
```php
if ( $item == 'edit.php' || $item == 'edit.php?post_type=' . $this->post_type->name ) return $key;
```

**Comment by omniacode** [comment]
@timotheemoulin - been trying to get this updated in the plugin for about a year now :(
