### ISSUE TITLE
Wrong third param on apply_filters

### ISSUE THREAD

**Issue by asadowski10** [kylephillips/wp-nested-pages#297]
Hi @kylephillips 

We have noticed an anomaly in your plugin which modifies the values of WordPress hooks.
In fact, in some apply_filters placed in views, you modify the return values.

Example: /wp-nested-pages/app/Views/partials/row.php:267
apply_filters (‘page_link’, $link, $this->post)

The last parameter is not a WP_Post but a post_id in the WordPress hook

To reproduce : 

`add_filter( 'post_link', function( string $permalink, WP_Post $post, bool $leavename ){ 
    /* my custom code */
    return $permalink;
} 10, 3  );`

Thanks,

**Comment by kylephillips** [comment]
The filter in question has been updated. The post_link now applies only to the `post` post_type – that filter receives a post object as the second parameter according to the documentation, unlike the page_link filter, which receives a post ID integer.

[post_link](https://developer.wordpress.org/reference/hooks/post_link/)
[page_link](https://developer.wordpress.org/reference/hooks/page_link/)

After an audit of core filter use, I found one other filter that was being incorrectly used – the_title.

If you come across any other anomalies, please open a separate issue.
