### ISSUE TITLE
Missing duplicate option on WPML translated pages

### ISSUE THREAD

**Issue by LucaPipolo** [kylephillips/wp-nested-pages#298]
## Problem
- The `Duplicate` button is missing on WPML translated pages. This makes impossible to duplicate pages in cases which regular WordPress + WPML allow it.

## How to reproduce
1. Create a page in the website default language (e.g. English)
2. Translate the above created page into another language (e.g. German)
3. On the backend page list, click on the three dots option. The `Duplicate` button is missing

## Suggested solution
- At [this point](https://github.com/kylephillips/wp-nested-pages/blob/master/app/Views/partials/row.php#L206), `wp-nested-pages` plugin is checking hiding the button if it's a WPML translated pages. Are there any reasons for this check? Removing this check from the condition solves the issue.

**Comment by kylephillips** [comment]
Duplicate issue closed in #309
