### ISSUE TITLE
feature request: use wp_insert_post

### ISSUE THREAD

**Issue by MeiKatz** [kylephillips/wp-nested-pages#303]
I am currently developing a plugin that checks if the permalink of a post changes and then tries to update this permalink in each related post. Also I am using Nested Pages. But: it is really hard to compare the previous permalink with the new permalink, because Nested Pages doesn't use `wp_insert_post` (or `wp_update_post`). Therefore I cannot use the hook `post_updated`. Is there any good reason why Nested Pages uses the `$wpdb` directly and not via `wp_insert_post`? Also: why does Nested Pages update every post entry even if only one post entry has moved? Therefore I get why it gets so slow with a lot of pages.

**Comment by MeiKatz** [comment]
@see https://github.com/kylephillips/wp-nested-pages/blob/ab8cb477cf948cda85afe961805759f2ae3508e2/app/Entities/Post/PostUpdateRepository.php#L69

**Comment by kylephillips** [comment]
Fixed in 0db6bfa99ee9c68f2305b5e01a7feca228faf048
