### ISSUE TITLE
Deprecated: Required parameter order

### ISSUE THREAD

**Issue by mspiessch** [kylephillips/wp-nested-pages#304]
Hi there, 

First thank's for the plugin! It's smoother to work with large amount of pages :) 

I'have a bug when I activate the plugin. I have search the problem on find that 

````
public function postTree($parent_id = 0, $post_type, $include_parent = true) // app/Entities/Post/PostRepository.php
````

should be replaced with 

````
public function postTree( $post_type, $parent_id = 0,  $include_parent = true) // app/Entities/Post/PostRepository.php
````

Thank's and best regards.

**Comment by kylephillips** [comment]
Closed [here](https://github.com/kylephillips/wp-nested-pages/commit/e7fbf8baf07deebc42ad7cc7b32ed3cc2e2d58b1)
