### ISSUE TITLE
Feature request: add hook to modify $row_classes in Listing.php

### ISSUE THREAD

**Issue by mjot** [kylephillips/wp-nested-pages#314]
Hello Kyle,

first thank you for your great plugin, it really makes the backend clearer.

I have a little feature request. Could you give developers the possibility to define custom `$row_classes` in the file `Listing.php` via apply_filters? We have extended the default wordpress listing using the 'post_class' [hook](https://developer.wordpress.org/reference/hooks/post_class/) to modify the rows there.

It would be great if we could extend the Nested Pages representation as well. it would also be enough for us if you output the post_classes of wordpress in the respective row, then no additional hook would be necessary.

Thanks for your answer in advance

**Comment by kylephillips** [comment]
Good suggestion. This is complete and will be included in the next release.
