### ISSUE TITLE
Feature Request: Making use of disableNestingClass

### ISSUE THREAD

**Issue by lstenner** [kylephillips/wp-nested-pages#317]
Hi,

nestedSortable seems to have the option to disable Nesting within a branch by giving the parent a class. The default class in the shipped version thats coming with wp-nested-pages has the class "mjs-nestedSortable-no-nesting" for that.

It would be nice if Nested Pages honored that class to prevent sorting inside a branch.

**Comment by kylephillips** [comment]
The next release will introduce a new filter, `nestedpages_row_parent_css_classes`. The filter will pass three parameters: the css classes, the post object, and the post type.

[Here is a Gist showing usage](https://gist.github.com/kylephillips/f2b94dc9b61470c6216b780291f89e39)
