### ISSUE TITLE
Adding new pages does not account for block templates

### ISSUE THREAD

**Issue by wonkeythemonkey** [kylephillips/wp-nested-pages#319]
With the WordPress Block Editor, it is possible to define a block template for a post type. For example, the following code registers a simple block template for the `page` post type:

```php
function my_theme_register_page_template()
{
    $block_template = [
        [
            'my-blocks/page-header', [ ]
        ],
        ['core/group',
            [
                'templateLock' => false,
            ],
            [
                [ 'core/paragraph', [] ]
            ]
        ]
    ];

    $post_type_object = get_post_type_object('page');
    $post_type_object->template_lock = 'all';
    $post_type_object->template = $block_template;
}
add_action('init', 'my_theme_register_page_template', 100, 1);
```

When you create a page by using the "New Page" button, either in standard WordPress or in the Nested Pages interface, the blocks defined in the template are added to the page.

There are several Nested Pages features that create new pages without immediately opening them in the Block Editor:  "Add Multiple", "Add New Child", "Insert Page Before", and "Insert Page After". When these pages are created, they do not automatically have the template blocks inserted into their content. This is a serious problem because the template often dictates that no blocks may be added to a page that are not part of the template, leaving a blank page that cannot be edited.

Is it possible for Nested Pages to honor the block template when creating a new page with these methods, so that the blocks in the block template are present as soon as the page is added?

**Comment by kylephillips** [comment]
It looks like there is no current way to hook into this functionality when creating a new post through the standard `wp_insert_post` function, which this plugin uses. It seems like the template is primarily added through the block editor when creating a new post through the standard interface.

I've added a new filter `nestedpages_new_post` that passes two parameters: the $post array to be inserted, and the form $data (which contains parameters like the parent_id, post_type, etc). This will be available in the next release. 

You may be able to hook into that and insert your blank block template as needed into the `post_content' param.

[Reference](https://wordpress.stackexchange.com/questions/364561/add-php-block-template-to-content-using-wp-insert-post)

I'll try to keep an eye out on any future WP core updates that could make this possible. I wasn't yet aware of block templates, and can definitely see the advantages to them.
