### ISSUE TITLE
Deleted Nested Pages Menu Keeps Recreating Even When Menu Sync is Completely Disabled (Reopen)

### ISSUE THREAD

**Issue by black-eye** [kylephillips/wp-nested-pages#322]
I've never used Menu Sync and probably never will in the future, so after I deactivate this option in the Settings, I want to get rid of the autogenerated Nested Pages menu as well. I can surely delete it, and it's gone, but only until I save the Nested Pages Settings again.

I already created the bug report a while ago (https://github.com/kylephillips/wp-nested-pages/issues/292), but it was closed without providing a solution.

Just a disclaimer - Menu sync IS disabled completely:

![obrazek](https://user-images.githubusercontent.com/5634870/152212040-7a43cc48-fea5-4834-9025-6192cd0b9cd8.png)

I want to point out, that the menu is recreated only when you save the Nested Pages Stettings again. Until then, everythink is ok.

Could you please look into it once again?
Thanks

**Comment by kylephillips** [comment]
The details about saving the Nested Pages settings again helped. This should be patched in the next release.

**Comment by black-eye** [comment]
Hello @kylephillips,
the problem still persists even in 3.1.21, despite the changelog says "Fixes issue where Nested Pages menu persists in some instances when “Disable menu completely” is checked/enabled."

After resaving the Nested Pages Settings, once deleted Nested Pages Menu reappears again.
