### ISSUE TITLE
default menu structure 

### ISSUE THREAD

**Issue by oxindustries** [kylephillips/wp-nested-pages#323]
Hi Kyle, 

Nested Pages is really a very nice plugin. I've it working on my clients site but whenever I move back from editing a page it goes directly to Default menu structure in stead of the nested page layout (see attached files). Anyway how to resolve this? Thanks!

![Schermafbeelding 2022-02-08 om 12 46 35](https://user-images.githubusercontent.com/99257832/152981027-eae14141-8ddb-4ac3-91aa-e40cd7fa85d9.png)
![Schermafbeelding 2022-02-08 om 12 46 59](https://user-images.githubusercontent.com/99257832/152981036-11c14e61-3abd-4d93-a2e5-0984a3ce7013.png)

**Comment by kylephillips** [comment]
I've been unable to recreate this issue. After editing a page and clicking the WP icon, the page redirects to the nested interface. If this continues, please provide detailed steps to replicate.
