### ISSUE TITLE
assets/js/nestedpages.js is provided minified only

### ISSUE THREAD

**Issue by PLUS-RobertEhrenleitner** [kylephillips/wp-nested-pages#324]
Both files, `nestedpages.js` as well as `nestedpages.min.js` contain the minified JavaScript source code. Please put the non-minified version into the repository.

**Comment by kylephillips** [comment]
All non-minified JS is available in the /lib directory [here](https://github.com/kylephillips/wp-nested-pages/tree/master/assets/js/lib). The JS is concatenated and minimized during the [build process](https://github.com/kylephillips/wp-nested-pages/blob/master/gulpfile.js)
