### ISSUE TITLE
How to create nestedpages.min.js?

### ISSUE THREAD

**Issue by PLUS-RobertEhrenleitner** [kylephillips/wp-nested-pages#325]
Since we did a modification to one of the JS files in the `lib` directory, I want to now how to rebuild the `nestedpages.min.js`.

Is it just:
````
> nestedpages.js; for i in lib/*.js; do (cat "$i"; echo) >> nestedpages.js; done
uglifyjs nestedpages.js -m --keep-fnames -o nestedpages.min.js
````
At least, I cannot see an error.

**Comment by kylephillips** [comment]
JS is compiled using a Gulp build process, so you'd want to clone this repo, run `npm install` and run `gulp`. You would also need to run `composer install` before installing the plugin in order to bring in autoloading.
