### ISSUE TITLE
Nested Pages plugin breaks when using PublishPress Permissions Pro

### ISSUE THREAD

**Issue by bwaltz** [kylephillips/wp-nested-pages#330]
We're using the PublishPress Permissions Pro plugin to manage permissions on our site. We have it set up where different user groups, created inside the Permissions plugin, only get access to read and edit certain pages within the hierarchy. 

This works well when Nested Pages is not enabled. When a user logs in, the only see the pages they are allowed to see. However, when Nested Pages is enabled, all the pages in their list disappear:

![Screen Shot 2022-10-26 at 9 31 09 AM](https://user-images.githubusercontent.com/2333967/198039480-657ed26f-8143-4c47-b572-14cdb8eab257.png)

What is causing the pages to disappear? Is this an incompatibility with the Permissions plugin?

**Comment by kylephillips** [comment]
I installed the plugin (thanks to them for a dev copy), and was unable to recreate this issue. Nested Pages uses core permissions checks throughout, so I'm not sure what would be causing this.

**Comment by bwaltz** [comment]
@kylephillips looking at this again. Seems like this is still an issue even with the latest versions of both plugins.

In our system, everyone has a specific user group in Permissions Pro and all the groups are configured like this (only the categories change).

![Screenshot 2024-08-12 at 1 47 07 PM](https://github.com/user-attachments/assets/3996279b-9b8e-4ad1-993b-6054640ca65e)

In terms of page permissions, users can only edit pages at a specific level. In the above example, users can only edit pages at or below `/academics/departments/programs/african-american-studies`.

This may add vital details.
