### ISSUE TITLE
Wrong comparision

### ISSUE THREAD

**Issue by alexsancho** [kylephillips/wp-nested-pages#333]
Hi, thanks for your work, 

seems that there's a typo on postclone script that prevents the cloning on post types other than pages

https://github.com/kylephillips/wp-nested-pages/blob/3023ec7bd0c09123032ac797c039145399af64d4/app/Entities/Post/PostCloner.php#L81

**Comment by kylephillips** [comment]
I'm unable to recreate the issue (able to clone other post types w/o issue). `np-redirect` is a hidden post type used by the plugin for creating links in the page hierarchy. The above script enables cloning on that post type (so if you clone the page and all of its child pages, the links are also included).
