### ISSUE TITLE
Feature request: Export and Import page order

### ISSUE THREAD

**Issue by fostira** [kylephillips/wp-nested-pages#339]
Thanks for great plugin and keeping up the development!

Here's an idea based on the needs we detected:

Would be nice to be able to export an order layout and import it on a different installation with the same pages in order to save time when you don't need to re-import whole pages or the WP installation.

A bonus would have been if it could create pages that are missing. 

We can think of it as a template that you might use to create or reorder many pages in few clicks.

**Comment by kylephillips** [comment]
Not sure how this would work, since the IDs of the pages would not be the same (no way to correctly associate one site's pages with the others. The ordering uses the core `menu_order` functionality/column, so in edge cases like this, I'd probably accomplish through the database directly.
