### ISSUE TITLE
License

### ISSUE THREAD

**Issue by noetro** [kylephillips/wp-nested-pages#340]
Hi, thank-you for all your open source contributions.

We would like to use nested pages in our Wordpress install, but I cannot find any mention to what licensing you are using.  Any chance you could clarify that by adding a license file ?

**Comment by kylephillips** [comment]
As a derivative work of WordPress, this plugin inherits the GNU public license as outlined [here](https://wordpress.org/about/license/). 

The license is stated in the plugin file [here](https://github.com/kylephillips/wp-nested-pages/blob/master/nestedpages.php#L17-L19).
