### ISSUE TITLE
Cross Site Scripting Vulnerability

### ISSUE THREAD

**Issue by omniacode** [kylephillips/wp-nested-pages#351]
Hey Kyle -

Hope that you are well. Security issue with the latest version of the plugin:

[https://patchstack.com/database/vulnerability/wp-nested-pages/wordpress-nested-pages-plugin-3-2-6-cross-site-scripting-xss-vulnerability?_a_id=431](https://patchstack.com/database/vulnerability/wp-nested-pages/wordpress-nested-pages-plugin-3-2-6-cross-site-scripting-xss-vulnerability?_a_id=431)

Wprdfence is also screaming about his on all of our client sites. Hoping for an update soon.

Thanks

**Comment by tD3rk** [comment]
Just wanted to add my voice that we're also seeing warnings for this everywhere and hoping a speedy fix can be deployed.

**Comment by lkraav** [comment]
Fortunately this vulnerability requires Admin privileges to execute on, but yes, watchdogs barking all across is still annoying.

**Comment by omniacode** [comment]
Thank you @kylephillips!
