### ISSUE TITLE
Deprecated: Calling get_class()

### ISSUE THREAD

**Issue by VovaChampion** [kylephillips/wp-nested-pages#354]
Hi, 
Moved to php 8.3 that causing warning  
`Deprecated: Calling get_class() without arguments is deprecated in /www/.../public/wp-content/plugins/wp-nested-pages/app/Entities/Listing/Listing.php on line 168`

Article: https://php.watch/versions/8.3/get_class-get_parent_class-parameterless-deprecated

**Comment by kylephillips** [comment]
This is resolved in the latest version, 3.2.8
