### ISSUE TITLE
WPML - Multiple Menus

### ISSUE THREAD

**Issue by kylephillips** [kylephillips/wp-nested-pages#62]
Look into WPML support, primarily option to toggle / set menus based on language.

**Comment by jackblackCH** [comment]
+1, currently if sync menus is active and we change the language a lot of magic problems appear when visiting the menu page.

**Comment by jackblackCH** [comment]
>May I ask at which time this feature will be integrated? High demand here and I think in community ;)

**Comment by kylephillips** [comment]
Closing this with the WPML branch merge. Due to the inner workings of WPML's menu synchronization, this wasn't possible. All synchronization will need to be triggered from WPML's interface, and unfortunately it will not be possible to support custom nested pages links when using WPML. The good news is, the primary language is still "syncable", and the magic problems should be fixed. Custom links can still be added under the Appearance > Menus interface and synced across languages.
