### ISSUE TITLE
Suggesting plugin as a features plugin for core

### ISSUE THREAD

**Issue by paaljoachim** [kylephillips/wp-nested-pages#83]
Hey Kyle

You have a great plugin! One that would fit nicely directly into core. 

I wrote an article showing a screenshot from various drag and drop reordering plugins and treeview plugins: http://easywebdesigntutorials.com/drag-and-drop-page-ordering-in-a-tree-page-view-wordpress/

WordPress has had a ticket going for many years in regards to drag and drop of posts/pages/etc and have also brought up tree view. https://core.trac.wordpress.org/ticket/2702

Merging your plugin into core and at the same time creating an updated look would be really nice.
These days there is a call for new feature plugins: https://make.wordpress.org/core/
It would be great if you would like to suggest your really useful plugin as a feature plugin.

**Comment by kylephillips** [comment]
Closing this per our email conversation.
