### ISSUE TITLE
Autoloading fails

### ISSUE THREAD

**Issue by metaodi** [kylephillips/wp-nested-pages#85]
I don't know what I'm doing wrong, but I can't get this plugin to work. I'm running it with PHP 5.5 and install it directly from this repository. Then I run `composer.phar install` to generate the autoloader and I keep getting the following error:

```
Fatal error: Class 'NestedPages\Bootstrap' not found in /var/www/content/plugins/wp-nested-pages/app/NestedPages.php on line 17
```

Version 1.1.9 of the plugin works perfectly but starting from 1.2.0, the class loading is somehow broken. Is this a bug? Or do I install this wrong? Any help would be appreciated.

**Comment by kylephillips** [comment]
I'll need to replicate… are you using something like wp-cli for the installation? Are you using composer for functionality in your install? Have you tried running composer update?

Version 1.2 was a significant rewrite. Prior to that, the composer autoloader wasn't being used.

**Comment by metaodi** [comment]
No I don't use wp-cli and I only use composer for wp-nested-pages. I guess I need to run it in order to get the autoloading to work. `composer update` doesn't work either.

What's the best way to install wp-nested-pages from source? I just cloned the repo (i.e. added it as a submodule) and then ran `composer install`. Is there anything else I need to do?

**Comment by kylephillips** [comment]
I ran the following test, and everything is working as expected on my end:

* Created a new WP install
* Cloned the repo into wp-content/plugins
* Ran `composer install`
* Ran `composer update`
* Activated the plugin through the WP admin

Can you verify that composer has been installed correctly? There should be a `vendor` directory in the main plugin directory if it has.

**Comment by metaodi** [comment]
I can install the plugin and it works, so I can drag and drop the pages, nest them etc.

The error above I get on the frontend, not in the admin dashboard. Very strange :confused: Do I need to change something in my theme?

**Comment by kylephillips** [comment]
Yes, that is strange. RE: theme changes, there is no front-end functionality in Nested Pages, so there would be nothing to change. 

I've updated the loading to only load on admin (there's no reason to initialize the plugin on the front end). If you grab the current master it should clear it up.

**Comment by metaodi** [comment]
Okay, that fixed my problem. I still don't understand why I had it in the first place, but anyway it's gone. Thanks for your help!!
