### ISSUE TITLE
Branching menu

### ISSUE THREAD

**Issue by paaljoachim** [kylephillips/wp-nested-pages#86]
Hey

What about closing and opening a menu branch similar to this plugin:
http://codecanyon.net/item/menu-management-enhancer-for-wordpress/full_screen_preview/529353

If a someone has a long submenu closing it up freeing visual space would be of help.

**Comment by kylephillips** [comment]
The primary purpose of NP is for enabling/enhancing the "nested" interface… not really the menu interface under appearance > menus. Can't see why using the above plugin would conflict with NP in any way, so I'm going to close this.
