### ISSUE TITLE
Admin menu item for custom post type disappears

### ISSUE THREAD

**Issue by metaodi** [kylephillips/wp-nested-pages#89]
Hi,

I currently have a very strange bug: if I add a custom post type and define it's `menu_position` to be `5` it disappears from the admin menu. I actually have several post types that I all defined to be at position 5 (this is basically me being lazy, i.e. copy/paste). When I do that, the first one disappears. If I define different menu positions everything is fine again, but still I think it's bad if a menu item disappears completely in this case. 

By looking at the code, I suspect the problem to be [in the `menu_position` method of the `EnabledMenus` class](https://github.com/kylephillips/wp-nested-pages/blob/8196fd7ae929d41d37dd08af954a6533ed13961a/app/Entities/AdminMenu/EnabledMenus.php#L132).

**Comment by metaodi** [comment]
Maybe the `menu_position` is not the problem after all. I just deployed the updated menu position to my production server, and it didn't work either. I found out that when I set post_type to public for the missing post type, it re-appears. The plugin seems to have problems with non-public post types.

**Comment by kylephillips** [comment]
Try the following and see if it resolves your issue:

Open app/Entities/PostType/PostTypeRepository.php

Comment out or remove line 14 (the public argument for the get_post_types function).

If it clears up your issue, I'll need to make a couple other updates to that method before pushing live.
