### ISSUE TITLE
Main menu is wiped when I create or delete a page

### ISSUE THREAD

**Issue by metaodi** [kylephillips/wp-nested-pages#91]
I currently have a very strange bug.

When the menu synchronisation is enabled (with a menu called "Nested Pages") and I create a new page, it wipes all elements of my "main_menu", so a different one than it should even sync. If I disable the menu sync, adding a page does not alter the "main_menu", which is what I would expect anyway.

But when I delete (i.e. move to trash) a page (no matter if menu sync is enabled or disabled), the main_menu is always wiped.

Do you have an idea why this happens?

**Comment by kylephillips** [comment]
This has been addressed in version 1.3.8, just pushed here and in the WP repository. There was a bug in the synchronization that was removing items outside of the generated nav menu.
