### ISSUE TITLE
"wrong order" of subpages after adding new subpage after moving another subpage

### ISSUE THREAD

**Issue by rainerberg** [kylephillips/wp-nested-pages#97]
wordpress 4.1.1
the procedure: 
- have a main page-1, add subpages page-1-1, page-1-2, page-1-3 with "add child" (1-1,1-2,1-3)
- move page-1-3 before page-1-1 (1-3,1-1,1-2)
- add subpage page-1-4 with "add child"
- page-1-4 ist displayed at fourth position (1-3,1-1,1-2,1-4 PLUGINVIEW All Pages) 
BUT is added at the second position (1-3,1-4,1-1,1-2 >WORDPRESSVIEW Default Pages)

**Comment by kylephillips** [comment]
Thanks for the detailed procedure… really helped debug this. It'll be corrected in the next release.
