### ISSUE TITLE
Bug: Empty Trash Button produces JS Error: Uncaught Typ Error:

### ISSUE THREAD

**Issue by jackblackCH** [kylephillips/wp-nested-pages#98]
Click on "Empty Trash" produces

 Uncaught TypeError: undefined is not a function

... in /wp-content/plugins/wp-nested-pages/assets/js/lib/bs-modal.js?ver=1.0 line 186
visible in log or wp-debugbar

Wordpress: 4.1.1
Nested Pages: 1.3.10
Setup: Multisite
WPML Activated

**Comment by chadwick37** [comment]
I'm getting the same errors when clicking the add link or add multiple buttons. The other modals seem to be working properly.

**Comment by kylephillips** [comment]
Would either of you mind testing this updated plugin?:

http://nestedpages.com/downloads/wp-nested-pages.zip

I'm having trouble replicating the issue, but based on the line number of the error, it seems to be a dependency issue.

**Comment by chadwick37** [comment]
That fixed it for me.

**Comment by kylephillips** [comment]
Thanks for the quick response. I'll push this out on wp.org.
