### ISSUE TITLE
Random reordering

### ISSUE THREAD

**Issue by jackblackCH** [kylephillips/wp-nested-pages#99]
We have over 250 pages with a hierarchy.

We have a problem with auto reordering.
3 editors are working together on the nested pages page, editing content but the editors are not moving the top level pages! It's a fixed order, nobody will change.

I can't reproduce the behavior but even the top level of the nested pages are all the time reordered by magic!... we are just editing sites from different account, not moving!
How may this reordering happen?

Setup: Multisite, WPML (only in 1 language currently), WP 1.11

**Comment by scottshefler** [comment]
First off, love the plugin! I'm having similar issues where all of a sudden items output in a random order. I have a very simple wp_query and works perfectly initially. Then somewhere along the way once people start adding posts it gets out of order. Going back and re-ordering any item seems to then fix the issue.

`
<?php
  $case_study_args = array(
    'post_type' => 'case_studies',
    'posts_per_page'=> 9,
    'orderby' => 'menu_order',
    'order' => 'ASC'
  );
  // Query
  $case_study_query = new WP_Query($case_study_args);
?>
`
